elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

keycloak:
    realm: ${KEYCLOAK_REAM:fc3-codeflix}
    host: ${KEYCLOAK_HOST:http://localhost:8443}
